In [1]:
# declare imports
import pandas as pd
import json

In [3]:
# retrieve data
filename = "default-cards-20260323090744.json"
with open(filename, 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data)

In [6]:
df['name_freq'] = df.groupby('name').id.transform('count')
df.drop_duplicates('name')[df.name_freq == 5].name.sample(5)

C:\Users\atnhe\AppData\Local\Temp\ipykernel_17892\53700084.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.drop_duplicates('name')[df.name_freq == 5].name.sample(5)

6577            Death Grasp
29452         Corpse Knight
43397           Boros Elite
3827     Yargle and Multani
56963     Expedition Raptor
Name: name, dtype: object

In [7]:
sub = df[df.name == 'Corpse Knight']
sub

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,...,attraction_lights,color_indicator,printed_type_line,printed_text,variation_of,life_modifier,hand_modifier,content_warning,defense,name_freq
29452,card,42e1033b-383e-49b4-875f-ccdc94e08c9d,0c77b805-728d-4ae4-88a9-223f4b7b52e0,[],NaN,NaN,193779.0,378312.0,Corpse Knight,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
53927,card,7aa3f166-c5d1-40f0-9b23-352424b8e13a,0c77b805-728d-4ae4-88a9-223f4b7b52e0,[612569],111098.0,NaN,491330.0,705857.0,Corpse Knight,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
59965,card,8859c03c-6c75-402f-9870-d4067a4ec4ed,0c77b805-728d-4ae4-88a9-223f4b7b52e0,[692275],137269.0,NaN,615028.0,808341.0,Corpse Knight,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
61281,card,8b45117b-8369-48fc-8e5d-8986e662d123,0c77b805-728d-4ae4-88a9-223f4b7b52e0,[466960],73311.0,69991.0,192504.0,378264.0,Corpse Knight,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
91600,card,cfbcf6e7-d7cf-4103-85b3-8d9d104587e1,0c77b805-728d-4ae4-88a9-223f4b7b52e0,[],NaN,NaN,194081.0,382578.0,Corpse Knight,en,...,NaN,NaN,NaN,NaN,8b45117b-8369-48fc-8e5d-8986e662d123,NaN,NaN,NaN,NaN,5

In [9]:
sub.columns

Index(['object', 'id', 'oracle_id', 'multiverse_ids', 'mtgo_id', 'arena_id',
       'tcgplayer_id', 'cardmarket_id', 'name', 'lang', 'released_at', 'uri',
       'scryfall_uri', 'layout', 'highres_image', 'image_status', 'image_uris',
       'mana_cost', 'cmc', 'type_line', 'oracle_text', 'colors',
       'color_identity', 'keywords', 'produced_mana', 'legalities', 'games',
       'reserved', 'game_changer', 'foil', 'nonfoil', 'finishes', 'oversized',
       'promo', 'reprint', 'variation', 'set_id', 'set', 'set_name',
       'set_type', 'set_uri', 'set_search_uri', 'scryfall_set_uri',
       'rulings_uri', 'prints_search_uri', 'collector_number', 'digital',
       'rarity', 'card_back_id', 'artist', 'artist_ids', 'illustration_id',
       'border_color', 'frame', 'full_art', 'textless', 'booster',
       'story_spotlight', 'prices', 'related_uris', 'purchase_uris',
       'mtgo_foil_id', 'power', 'toughness', 'flavor_text', 'edhrec_rank',
       'penny_rank', 'all_parts', 'promo_types', 'security_stamp',
       'card_faces', 'preview', 'watermark', 'frame_effects', 'loyalty',
       'printed_name', 'resource_id', 'tcgplayer_etched_id', 'flavor_name',
       'attraction_lights', 'color_indicator', 'printed_type_line',
       'printed_text', 'variation_of', 'life_modifier', 'hand_modifier',
       'content_warning', 'defense', 'name_freq'],
      dtype='object')

In [10]:
sub[['name', 'released_at', 'mana_cost', 'cmc', 'type_line', 'oracle_text', 'colors', 'keywords', 'legalities', 'reprint', 'set_id', 'set', 'set_name']]

,name,released_at,mana_cost,cmc,type_line,oracle_text,colors,keywords,legalities,reprint,set_id,set,set_name
29452,Corpse Knight,2019-07-12,{W}{B},2.0,Creature — Zombie Knight,"Whenever another creature you control enters, ...","[B, W]",[],"{'standard': 'not_legal', 'future': 'not_legal...",True,bb017236-6da1-4558-a8bd-cf020e964530,pm20,Core Set 2020 Promos
53927,Corpse Knight,2023-04-21,{W}{B},2.0,Creature — Zombie Knight,"Whenever another creature you control enters, ...","[B, W]",[],"{'standard': 'not_legal', 'future': 'not_legal...",True,6bba5de9-5afb-42af-a7eb-24ac854bf671,moc,March of the Machine Commander
59965,Corpse Knight,2025-02-14,{W}{B},2.0,Creature — Zombie Knight,"Whenever another creature you control enters, ...","[B, W]",[],"{'standard': 'not_legal', 'future': 'not_legal...",True,d33ef7a4-41bb-4f16-bad3-b3ee13c257e6,drc,Aetherdrift Commander
61281,Corpse Knight,2019-07-12,{W}{B},2.0,Creature — Zombie Knight,"Whenever another creature you control enters, ...","[B, W]",[],"{'standard': 'not_legal', 'future': 'not_legal...",False,4a787360-9767-4f44-80b1-2405dc5e39c7,m20,Core Set 2020
91600,Corpse Knight,2019-07-12,{W}{B},2.0,Creature — Zombie Knight,"Whenever another creature you control enters, ...","[B, W]",[],"{'standard': 'not_legal', 'future': 'not_legal...",False,4a787360-9767-4f44-80b1-2405dc5e39c7,m20,Core Set 2020

In [11]:
m20 = sub[sub.set == 'm20']
for col in m20.columns:
    if len(m20.drop_duplicates(col)) > 1:
        print(col)

id
multiverse_ids
mtgo_id
arena_id
tcgplayer_id
cardmarket_id
uri
scryfall_uri
image_uris
foil
finishes
variation
rulings_uri
collector_number
prices
related_uris
purchase_uris
preview
variation_of

In [12]:
m20.foil

61281     True
91600    False
Name: foil, dtype: bool

In [15]:
akki = df[df.name == 'Akki Ronin']
len(akki)

2

In [16]:
df['is_akki'] = df.name.apply(lambda x: int('Akki Ronin' in x))
print(len(df[df.is_akki == 1]))

3

In [18]:
df[df.is_akki == 1][['name']]

                name
5630    A-Akki Ronin
66343     Akki Ronin
110059    Akki Ronin

In [19]:
df[df.is_akki == 1].head()

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,...,color_indicator,printed_type_line,printed_text,variation_of,life_modifier,hand_modifier,content_warning,defense,name_freq,is_akki
5630,card,0c780e37-91b1-4fe1-85c9-7007d91209d5,1be31774-decb-4d33-900c-5ec6e725d803,[],NaN,85628.0,NaN,NaN,A-Akki Ronin,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
66343,card,96f15754-1ca6-45b0-a7de-2fe507df2a1a,4b4c76e1-c480-4d10-93d4-483ef2debc4b,[548433],97190.0,79560.0,262786.0,608229.0,Akki Ronin,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1
110059,card,fa16ee8e-d33a-40e9-9956-e345f0511819,4b4c76e1-c480-4d10-93d4-483ef2debc4b,[553228],NaN,79870.0,262852.0,608321.0,Akki Ronin,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1

In [20]:
df[df.is_akki == 1].digital

5630       True
66343     False
110059    False
Name: digital, dtype: bool

In [21]:
df.columns

Index(['object', 'id', 'oracle_id', 'multiverse_ids', 'mtgo_id', 'arena_id',
       'tcgplayer_id', 'cardmarket_id', 'name', 'lang', 'released_at', 'uri',
       'scryfall_uri', 'layout', 'highres_image', 'image_status', 'image_uris',
       'mana_cost', 'cmc', 'type_line', 'oracle_text', 'colors',
       'color_identity', 'keywords', 'produced_mana', 'legalities', 'games',
       'reserved', 'game_changer', 'foil', 'nonfoil', 'finishes', 'oversized',
       'promo', 'reprint', 'variation', 'set_id', 'set', 'set_name',
       'set_type', 'set_uri', 'set_search_uri', 'scryfall_set_uri',
       'rulings_uri', 'prints_search_uri', 'collector_number', 'digital',
       'rarity', 'card_back_id', 'artist', 'artist_ids', 'illustration_id',
       'border_color', 'frame', 'full_art', 'textless', 'booster',
       'story_spotlight', 'prices', 'related_uris', 'purchase_uris',
       'mtgo_foil_id', 'power', 'toughness', 'flavor_text', 'edhrec_rank',
       'penny_rank', 'all_parts', 'promo_types', 'security_stamp',
       'card_faces', 'preview', 'watermark', 'frame_effects', 'loyalty',
       'printed_name', 'resource_id', 'tcgplayer_etched_id', 'flavor_name',
       'attraction_lights', 'color_indicator', 'printed_type_line',
       'printed_text', 'variation_of', 'life_modifier', 'hand_modifier',
       'content_warning', 'defense', 'name_freq', 'is_akki'],
      dtype='object')

In [25]:
df[df.flavor_name.notnull()][['name', 'flavor_name']]

                              name                 flavor_name
264              Thorn of Amethyst            Shards of Narsil
619                       Solitude                     Yojimbo
1094      Varragoth, Bloodsky Sire    Tiffany, Bride of Chucky
1182    Kenrith, the Returned King  Théoden, Strength Restored
2172                  Bow of Nylea            The Grim Whisper
...                            ...                         ...
111109              Mouth of Ronom                Redhorn Pass
111150               Akroma's Will      Blessing of the Oracle
111633                   Dirge Bat      Battra, Dark Destroyer
112006              Ashnod's Altar       Sir Bedivere's Scales
112172              Deepglow Skate        Man Ray, Eco Avenger

[543 rows x 2 columns]